import {
  angelus,
  aquaBenedicta,
  blessing,
  cure,
  decreaseAgi,
  heal,
  holyLight,
  increaseAgi,
  pneuma,
  repelEvil,
  ruwach,
  teleport,
} from "../../acolyte/acolyte/skills";
import { safetyWallPriest } from "../../acolyte/priest/skills";
import { attentionConcentrate, owlsEye } from "../../archer/archer/skills";
import {
  coldBolt,
  fireBall,
  fireBolt,
  frostDiver,
  increaseSpRecovery,
  lightningBolt,
  napalmBeat,
  sight,
  soulStrike,
  stoneCurse,
  thunderstorm,
} from "../../mage/mage/skills";
import {
  axeMastery,
  cartRevolution,
  cursedTomahawk,
  efficiency,
  enlargeWeightLimit,
  itemAppraisal,
  mammonite,
  pushcartMastery,
} from "../../merchant/merchant/skills";
import {
  bash,
  endure,
  increaseHpRecovery,
  ironDefense,
  magnumBreak,
  oneHandQuicken,
  provoke,
  swordMastery,
} from "../../swordsman/swordsman/skills";
import {
  detoxify,
  doubleAttack,
  envenom,
  hiding,
  improveDodge,
  increaseSpeed,
  quickStrike,
  steal,
  throwSand,
} from "../../thief/thief/skills";

export const superNoviceSkills = [
  swordMastery,
  oneHandQuicken,
  increaseHpRecovery,
  ironDefense,
  bash,
  magnumBreak,
  provoke,
  endure,
  angelus,
  aquaBenedicta,
  blessing,
  cure,
  decreaseAgi,
  repelEvil,
  heal,
  holyLight,
  increaseAgi,
  pneuma,
  ruwach,
  teleport,
  detoxify,
  doubleAttack,
  envenom,
  hiding,
  improveDodge,
  steal,
  quickStrike,
  increaseSpeed,
  throwSand,
  attentionConcentrate,
  owlsEye,
  axeMastery,
  enlargeWeightLimit,
  itemAppraisal,
  mammonite,
  pushcartMastery,
  cursedTomahawk,
  efficiency,
  cartRevolution,
  coldBolt,
  fireBall,
  fireBolt,
  frostDiver,
  increaseSpRecovery,
  lightningBolt,
  napalmBeat,
  safetyWallPriest,
  sight,
  soulStrike,
  stoneCurse,
  thunderstorm,
];
